### ISSUE TITLE
Self referencing model

### ISSUE THREAD

**Issue by mehdiym** [graphql-python/graphene-mongo#10]
Hello and thx for your lib,

I'd like to self-reference a model, but I'm not sure how to do it as I'm quite new to Python, what I do is:

```
class Player(Document):
    created_on = DateTimeField(default=datetime.now, db_field='d')
    name = StringField(required=True, db_field='n')

Player.friends = ListField(ReferenceField(Player))
```

But I get an `AttributeError: 'NoneType' object has no attribute '_type'` in `python3.6/site-packages/graphene_mongo/converter.py`

Am I doing it wrong or is it not possible?

**Comment by abawchen** [comment]
@mehdiym:
It's a good point!

Graphene-Mongo does not support self-reference yet, and I am working on it now. Hope I can get back to you soon.

**Comment by abawchen** [comment]
@mehdiym : The feature is supported on the updated `master` or `pypi 0.1.4`, but I find another issue #12 during the self-reference implementation :(

Please let me know if you need anything of self-reference, if not, I will close this one, and will fix above issue in another pull request.

Thanks.

**Comment by mehdiym** [comment]
Thank you @abawchen it works great now :)
As I'd like to have friends specific fields (eg. affinity score), next thing I'll need is the support for list of embedded docs. Keep up the good work.

**Comment by abawchen** [comment]
@mehdiym : I am glad to notify you the version `0.1.5` is supporting ListField(EmbeddedDocumentField) now.

Your request makes me more productive. :stuck_out_tongue_winking_eye:

**Comment by mehdiym** [comment]
Wow, you did it fast, thank you very much. I'll try that soon (it's a personal project on my spare time, for now anyway)

**Comment by marvinkome** [comment]
This doesn't work though
```
class User(db.Document):
    # pylint:disable=no-member
    meta = {'strict': False}
    email = db.StringField(required=True, unique=True)
    password_hash = db.StringField(required=True)
    fullname = db.StringField()
    contacts = db.ListField(db.ReferenceField('self')) 
```
i don't really understand why.
it shows field doesn't exist in graphqli
