### ISSUE TITLE
Support for cursor based pagination

### ISSUE THREAD

**Issue by mpgalaxy** [graphql-python/graphene-mongo#106]
Hi,

how can I use cursor based pagination (page=page, per_page=...) with your library ? I can't modify the mongo request using something like this:
```python
def resolve_users(self, info):
    	return list(UserModel.objects.find({...}).sort(...).limit(limit))
```
because then I get `'QuerySet' object has no attribute 'find' `

Please provide information regarding this functionality or implement this feature.

**Comment by svanburen** [comment]
try using `limit` with `skip`:

```python
def resolve_users(self, info):
    	return list(UserModel.objects(query).sort(...).skip(x).limit(limit))
```

you'll want to calculate the skip based on the page number and page size, of course

**Comment by mpgalaxy** [comment]
@svanburen : This is what I try to avoid. I want to use cursor based pagination with page and per_page params without the need of count(). I tried to use this library with pagination by flask_mongoengine, but it doesn't work. It inserts first:1 in the query which results in a `Not a query object` error:
```
def resolve_users(self, info, page=None):
    	return list(UserModel.objects(query).paginate(page=page, per_page=4)
```

**Comment by svanburen** [comment]
It looks like in your case, you probably just want to omit the "query" parameter to `.objects`:

```python
def resolve_users(self, info):
        return list(UserModel.objects().skip(5).limit(3))
```

**Comment by mpgalaxy** [comment]
@svanburen : This works, but how can I do a find() before limit ?
I need to be able to do a
```
return list(UserModel.objects().find({'_id' > last_id}).sort(sort).limit(per_page))
```
How can I do this with this library ?

**Comment by svanburen** [comment]
@mpgalaxy perhaps something like this?:

```python
return list(UserModel.objects(id__gte=last_id).sort(sort).limit(per_page))
```

for reference: http://docs.mongoengine.org/guide/querying.html#query-operators

also, I see that you're using '_id' - you may want to replace the `id__gte` above with whatever the primary key is defined in your UserModel (I put `id` above, but you'll want to replace that - so if it's user_id, do this:

```python
return list(UserModel.objects(user_id__gte=last_id).sort(sort).limit(per_page))
```
)

hopefully that helps!

**Comment by mpgalaxy** [comment]
Thank you very much! :) I will give it a try tomorrow.
Currently I implemented pagination via skip and limit, which is suitable for small datasets:
```python
def resolve_users(self, info, page=None, per_page=None):
        if page <= 0 or per_page <= 0:
            raise Exception("Values of page and per_page must be >0!")
        elif page == 1:
            return list(UserModel.objects.limit(per_page))
        else:
            return list(UserModel.objects.skip((page-1)*per_page).limit(per_page))
```
I have to make sure that the ids are sorted ascending. Currently the library returns them sorted ascending, but an option for that would be nice. ;) I'll report back on my results.

BTW: How can I send a 404 response with this lib ? 
Throwing an Exception is not the best way to do this, because you still get status 200. ;)

Thanks again and best regards ;)

**Comment by svanburen** [comment]
I don't have a great answer for you for flask / 404s; typically in GraphQL rather than setting a HTTP response code you'll populate the errors dict, and I'd imagine the flask mutations wouldn't be so far from the other examples.

For sorting, you can use `order_by` to sort:

```python
return list(UserModel.objects(user_id__gte=last_id).order_by(...).limit(per_page))
```

good luck!

**Comment by mpgalaxy** [comment]
Hi, thank you very much, you really helped me a lot. I think I can close this issue now. ;)
