### ISSUE TITLE
Support for List of GenericReferenceFields

### ISSUE THREAD

**Issue by fabiontop** [graphql-python/graphene-mongo#114]
Working with a simple GenericReferenceField works fine. But as mentioned in #70 support for a List of GenericReferenceFields would be great. Thank you in advance!

**Comment by fabiontop** [comment]
I solved it by using a List of ReferenceField with self reference. I didn't notice that this was possible.

**Comment by lsmar** [comment]
Now it is possible to use List of GenericReferenceFields. Version 0.2.10 or above.
