### ISSUE TITLE
Query takes too much time (more than 5 minutes  to retrieve first 10 documents)

### ISSUE THREAD

**Issue by mtech2008** [graphql-python/graphene-mongo#115]
In "products" collection I have around 3000000 documents in a collection and I want to paginate it.
I am using the following query:

{
  allProducts(first:10){
    edges{
      node{
        brandname
      }
      cursor
    }
    pageInfo{
      hasPreviousPage
      hasNextPage 
      startCursor
      endCursor
    }
  }
}
and it either fails or takes too much time to fetch the documents. Please tell me what I am doing wrong.

**Comment by sostholmwork** [comment]
I've also got this issue.

**Comment by abawchen** [comment]
Maybe related to #125, that I will use #125 to follow up, close this one.
