### ISSUE TITLE
Missing LICENSE as part of the sdist

### ISSUE THREAD

**Issue by KingDarBoja** [graphql-python/graphene-mongo#133]
This python package lacks a License file as the other on graphql-python, making it difficult to be published on conda-forge, as this is a requirement for the pipeline to pass.

Also, would be great if there is some kind of changelog on the releases GH tab, as there isn't any CHANGELOG file on the repo.

I noticed the released version is currently at 0.2.10 but the GH releases is stuck at 0.2.7.

Cheers!

**Comment by abawchen** [comment]
@KingDarBoja : I have added LICENSE in #134, please help check it.
And I will try to work on releasing notes or change log for the following releases.

**Comment by KingDarBoja** [comment]
Just provide some review, you are missing the `MANIFEST.in` file. Please take a look at [graphql-core-next](https://github.com/graphql-python/graphql-core-next/blob/master/MANIFEST.in) as example. 😄
