### ISSUE TITLE
Graphene v3 compatibility

### ISSUE THREAD

**Issue by fhennig** [graphql-python/graphene-mongo#154]
Graphene v3 is still in beta, but pretty stable now (https://github.com/graphql-python/graphene/wiki/v3-release-notes#graphene-schema-no-longer-subclasses-graphqlschema-type), it would be great if graphene-mongo could be made compatible.

Only the `graphene` package has to be updated. I ran the tests in the repo locally with graphene v3.0b5 and 27/91 tests failed.

**Comment by Lwackp** [comment]
@arunsureshkumar why was the graphene dependency pinned to beta release`3.0b7` in https://github.com/graphql-python/graphene-mongo/pull/172 ? Graphene 3.0.0 was released on Nov 13, 2021

**Comment by Lwackp** [comment]
I've created https://github.com/graphql-python/graphene-mongo/pull/186 to address this

**Comment by abhinand-c** [comment]
@arunsureshkumar This issue has been resolved, we can safely close it.
