### ISSUE TITLE
Most versions in the pypi are wrongfully uploaded

### ISSUE THREAD

**Issue by jkuball** [graphql-python/graphene-mongo#170]
It's a little bit strange to have to report this, but it seems like all released versions on the pypi are wrong. The source code attached to the Github Releases seems to be wrong also.

The only way to install a new version of this library reliably is to use pips vsc support to install from a specific commit sha.

This has probably something to do with the never changing variable of `graphene_mongo.__version__`, which should be integrated into the release cycle too.

**Comment by abawchen** [comment]
@jkuball : thanks for addressing this issue, I will submit the latest version later.

**Comment by rish-ablacon** [comment]
@abawchen When is the next release planned and would it  add support of EnumField?

**Comment by dhulmul** [comment]
@abawchen When is the next release planned and would it add support of EnumField?

**Comment by blochs** [comment]
Did this ever get solved? I feel like I’m missing some great stuff without version updates

**Comment by abawchen** [comment]
it's a bit late -- I have tag a new version 0.2.14 align with master code. Feel free to ping me or re-open it if necessary.
