### ISSUE TITLE
`graphql_relay` dependency error

### ISSUE THREAD

**Issue by fabianriewe** [graphql-python/graphene-mongo#189]
Using `graphql-relay==3.1.4` and `graphene-mongo==0.2.14` creates an error due to a rename of `graphql_relay.connection.arrayconnection` to `graphql_relay.connection.array_connection`. There are two imports which need to be updated.

**Comment by RoyalGoose** [comment]
i have same error, did you fix it?

**Comment by blochs** [comment]
https://github.com/graphql-python/graphene-mongo/pull/191
