### ISSUE TITLE
How to filter a query by a list of ids in GraphQL using graphene-mongo?

### ISSUE THREAD

**Issue by vkresch** [graphql-python/graphene-mongo#190]
Basically I have the same question like in this [SO question](https://stackoverflow.com/questions/54218505/how-to-filter-a-query-by-a-list-of-ids-in-graphql-using-graphene-django) but for graphene_mongo? 
Is it possible? This [issue](https://github.com/graphql-python/graphene-mongo/issues/82) might be related. 

In the answer one way is to set the `filterset_class` with a custom class `SampleFilter`. Is there an equivalent for graphene-mongo?

Thanks in advance!

**Comment by vkresch** [comment]
Closing since [solution](https://github.com/graphql-python/graphene-mongo/issues/82#issuecomment-784027110) from @dscso solved my problem. Big thanks!

I defined a custom filter:
```python
class ProductFilter(graphene.InputObjectType):
    tags__in = graphene.List(graphene.String, name="tags_in", description="Product has to have ONE of the provided tags")
    tags__all = graphene.List(graphene.String, name="tags_all", description="Product has to have all provided tags")
```
which I then passed to the Query class (note I use `graphene_mongo.MongoengineConnectionField` here instead of `graphene.Field`):

```python
class Query(graphene.ObjectType):
    class Meta:
        description = "Root Query"

    node = Node.Field(QueryProductsSchema)
    query_products = graphene_mongo.MongoengineConnectionField(QueryProductsSchema, filters=ProductFilter())

    def resolve_query_products(self, info, **kwargs):
        return list(models.Product.objects(**kwargs.get("filters", {})))
```
 and now I can filter with this query:
```graphql
{
  queryProducts(filters: {
    tags_in: ["ww"],
  }) {
    products {
      tags
    }
  }
}
```

**Comment by dscso** [comment]
Actually I now stopped using graphene Mongo because its too much boilerplate. I use [Ariadne](https://ariadnegraphql.org/) now. Its easier for my usecase... I just recommend taking a look :)
