### ISSUE TITLE
Can I use 'MongoengineConnectionField' without 'edges'?

### ISSUE THREAD

**Issue by xiangxn** [graphql-python/graphene-mongo#194]
current:
`users {
    edges {
      node {
        id
      }
    }
}`

What I want is:
`
users {
        id
}`

**Comment by abhinand-c** [comment]
MongoengineConnectionField is implemented as per [Relay Spec](https://relay.dev/graphql/connections.htm). We can't deviate from that.

What might be looking is a simple **ListField** (something without pagination).

**Comment by abhinand-c** [comment]
@arunsureshkumar I think we can close this issue.
