### ISSUE TITLE
graphene-mongo not compatible with pymongo 4.0 or above

### ISSUE THREAD

**Issue by leonardwellthy** [graphql-python/graphene-mongo#197]
### Error message

Running the tutorial example at https://graphene-mongo.readthedocs.io/en/latest/tutorial.html returns the following error
```json
{
  "errors": [
    {
      "message": "'Cursor' object has no attribute 'count'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allEmployees"
      ]
    }
  ],
  "data": {
    "allEmployees": null
  }
}
```

### Underlying cause

`pymongo.cursor.Cursor.count()` was deprecated in pymongo 3.7.0 and removed in pymongo 4.0. See [the pymongo changelogs](https://pymongo.readthedocs.io/en/stable/changelog.html)

### Solution

The following line in [fields.py](https://github.com/graphql-python/graphene-mongo/blob/v0.2.14/graphene_mongo/fields.py#L350) needs to be replaced with a call to [pymongo.collection.Collection.count_documents](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.count_documents)
```
count = mongoengine.get_db()[self.model._get_collection_name()].find(args_copy).count()
```

### Temporary workaround

`pip install pymongo==3.12.0`

**Comment by krawalli** [comment]
yes, its working when line is changed to:
```
count = mongoengine.get_db()[self.model._get_collection_name()].count_documents(args_copy)
```
