### ISSUE TITLE
Is Project Dead

### ISSUE THREAD

**Issue by blochs** [graphql-python/graphene-mongo#199]
There's been no movement from maintainers or a release in >6 months and it was faulty and not patched, is this project dead? 

cc @abawchen

**Comment by abawchen** [comment]
@blochs : it's a good question xD

I start this as a side project that I don't actually use it in my job, and I have limit resource (time) to maintain it anymore.
So you can say it's dying, and I would more than happy if someone can take it as an owner/maintainer, or fork it to keep it compatible with the latest graphql version.

**Comment by erikwrede** [comment]
This isn't a project I'm maintaining but I'd strongly advise against forking, since most  users won't see the new fork.

**Comment by blochs** [comment]
@abawchen I can see if the company I work for is interested in taking over as a maintenance group...we use it heavily so it might make sense.

**Comment by blochs** [comment]
@abawchen Can you at least take a look at the open PR's, see if we can merge those along?

**Comment by erikwrede** [comment]
@blochs If you get an okay from company, I think we can definitely look into hooking you up with the necessary roles. 
Final word is of course @abawchen's as he is the project maintainer here. 
I'm mainly taking care of `graphene` and `-sqlalchemy`, but it's beneficial for the health of the graphene ecosystem if we try to keep the plugin-libraries actively maintained, so I want to assist where I can!

**Comment by blochs** [comment]
@erikwrede @abawchen We have approval, please let me know next steps, or if you'd like to proceed with DM's/e-mails.

**Comment by erikwrede** [comment]
Sounds great! Let's wait & hear what @abawchen has to say 🙂

**Comment by blochs** [comment]
@abawchen Any updates here? Love to get this transition going.

**Comment by abawchen** [comment]
@erikwrede @blochs : I am more than happy there is someone can make this project alive, so maybe @erikwrede can help grant more access to @blochs

**Comment by erikwrede** [comment]
Thanks @abawchen, great to get this started!
@blochs please contact me on Slack so we can figure out next steps & who to invite to the project! 
https://join.slack.com/t/graphenetools/shared_invite/enQtOTE2MDQ1NTg4MDM1LTA4Nzk0MGU0NGEwNzUxZGNjNDQ4ZjAwNDJjMjY0OGE1ZDgxZTg4YjM2ZTc4MjE2ZTAzZjE2ZThhZTQzZTkyMmM
