### ISSUE TITLE
Types are unaware of parent class attributes defined on child model

### ISSUE THREAD

**Issue by msholty-fd** [graphql-python/graphene-mongo#24]
First of all, thank you for writing this library. I've been wanting to try GraphQL out with my current project but didn't want to have to create an entire new backend application from scratch. I can reuse my existing models thanks to this library, way cool 👍 🥇 

Now for my issue...

I have a parent/child relationship defined like this:

```
from mongoengine import Document

class Parent(Document):
    bar = StringField()

class Child(Parent):
    baz = StringField()
```

When I defined my schema and attempt to query against the `Child` model, it says `Unknown argument "bar" on field "child" of type "Query"`

My query:
```
{
  child(bar:"a valid value") {
    edges {
      node {
        bar
        baz
      }
    }
  }
}
```

```
from graphene_mongo import MongoengineConnectionField, MongoengineObjectType
from app.models import Child as ChildModel

class Child(MongoengineObjectType):
    class Meta:
        model = ChildModel
        interfaces = (Node,)

class Query(graphene.ObjectType):
    node = Node.Field()
    child = MongoengineConnectionField(Child)

    schema = graphene.Schema(query=Query, types=[Child])
```

I may just be misusing the library, or perhaps this is a feature that isn't implemented yet.  If the feature hasn't been implemented yet I am up for taking a stab at it. Is there a way for my schema to infer the parent's attributes based on how I define them like the above example? Thank you again!

**Comment by abawchen** [comment]
@msholty-fd 
Thanks for addressing this issue, which is a great feature I just missed before.
It's now on `0.1.10` and `master` branch as well.

Feel free to re-open it if any problem.
