### ISSUE TITLE
edges & node attributes in result set

### ISSUE THREAD

**Issue by SoyYoRafa** [graphql-python/graphene-mongo#37]
Hi,
I am wondering why there is an edges and nodes attributes in the result set? It seems to break the concept of being able to have a consistent object model, query language and result set.

**Comment by abawchen** [comment]
Hi,
You can refer https://stackoverflow.com/questions/42622912/in-graphql-whats-the-meaning-of-edges-and-node or https://dev-blog.apollodata.com/explaining-graphql-connections-c48b7c3d6976 for the connection in the GraphQL.
