### ISSUE TITLE
Is there a way to filter results?

### ISSUE THREAD

**Issue by git-albertomarin** [graphql-python/graphene-mongo#4]
Do you have a way to filter queries? I understand that the graphene-django project relied on django-filter for query filtering. Is there something similar already implemented in this project?

I am trying to perform the following query:

```
query {
    allUsers(name: "foo"){
        edges{
            node{
                id,
                name
            }
        }
    }
}
```

**Comment by abawchen** [comment]
@git-albertomarin : I am still working on it, and hope it can be resolved soon.

**Comment by abawchen** [comment]
@git-albertomarin 

Now you can refer https://github.com/abawchen/graphene-mongo/blob/master/graphene_mongo/tests/test_query.py#L296 for the basic filtering, and I do not worked on other filter usage but only `=` comparison at this moment.

Feel free to feedback or submit other issues.
