### ISSUE TITLE
unable to install via pip - Some packages may not be found!

### ISSUE THREAD

**Issue by ahmad88me** [graphql-python/graphene-mongo#40]
Error:
Download error on https://pypi.python.org/simple/pytest-runner/: EOF occurred in violation of protocol (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)

I resolved the problem by:
1. I have to go to https://pypi.org/simple/pytest-runner/
2. download pytest_runner-4.2-py2.py3-none-any.whl
3. run pip install ./pytest_runner-4.2-py2.py3-none-any.whl
4. pip install graphene-mongo

**Comment by abawchen** [comment]
@ahmad88me 

Would you please provide your python, pip version and os as well? Since I can't reproduce it on my side.

**Comment by ahmad88me** [comment]
Sure, 
pip 10.0.1
Python 2.7.10
MacOS 10.12.6
