### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_type'

### ISSUE THREAD

**Issue by mtech2008** [graphql-python/graphene-mongo#57]
I am receiving an error  node = kv[1].get_type()._type._meta
AttributeError: 'NoneType' object has no attribute '_type'

when I am using "EmbeddedDocument(LatLang)"

class LatLng(EmbeddedDocument):
    lat = FloatField()
    lng =  FloatField()

class User(Document):
    email = StringField(required=True)
    first_name = StringField(max_length=50)
    last_name = StringField(max_length=50)
    location = EmbeddedDocumentField(LatLng)

**Comment by abawchen** [comment]
@mtech2008
Would you give it a try on `0.1.19` or the updated master?
I fixed some error if the reference field is inherited from `EmbeddedDocument`, you can refer following test case to double-check.

https://github.com/graphql-python/graphene-mongo/blob/master/graphene_mongo/tests/models.py#L90

https://github.com/graphql-python/graphene-mongo/blob/master/graphene_mongo/tests/types.py#L136

https://github.com/graphql-python/graphene-mongo/blob/master/graphene_mongo/tests/test_relay_query.py#L733

Feel free to re-open it, and provide more sample codes would be help.

**Comment by sjakati98** [comment]
I am experiencing the same error. Is there any way I can help. Would love to be able to use embedded documents in my schema.

**Comment by abawchen** [comment]
@mtech2008 & @sjakati98 

Maybe that's the cause -- currently, we have to define `LatLngType` as follows, only that graphene-mongo knows how to take care it -- it's won't be auto-registered at this moment.

Please let me know whether is works or not.

```python
import graphene
from mongoengine import connect
from mongoengine.fields import (
    Document, EmbeddedDocument,
    FloatField, StringField, EmbeddedDocumentField
)

from graphene_mongo import MongoengineConnectionField, MongoengineObjectType

connect('graphene-mongo-test', host='mongomock://localhost', alias='default')

class LatLng(EmbeddedDocument):
    lat = FloatField()
    lng = FloatField()

class User(Document):
    email = StringField(required=True)
    first_name = StringField(max_length=50)
    last_name = StringField(max_length=50)
    location = EmbeddedDocumentField(LatLng)


class LatLngType(MongoengineObjectType):

    class Meta:
        model = LatLng


class UserNode(MongoengineObjectType):
    
    class Meta:
        model = User
        interfaces = (graphene.Node,)


class Query(graphene.ObjectType):
    
    all_users = MongoengineConnectionField(UserNode)

query = '''
query {
    allUsers {
        edges {
            node {
                email,
                location {
                    lat,
                    lng
                }
            }
        }
    }
}
'''

schema = graphene.Schema(query=Query)
result = schema.execute(query)
```

**Comment by abawchen** [comment]
@gifteconomist
> all_briefs = MongoengineConnectionField(Brief)

typo here? should be `MongoengineConnectionField(BriefNode)`

Following code works for me:

```python
import graphene
from mongoengine import connect
from mongoengine.fields import (
    Document, EmbeddedDocument,
    FloatField, StringField, EmbeddedDocumentField
)

from graphene_mongo import MongoengineConnectionField, MongoengineObjectType


class Brief(Document):
    meta = {
        'allow_inheritance': True,
        'strict': False
    }
    id = StringField(primary_key=False)
    topic = StringField(required=True)

class BriefNode(MongoengineObjectType):
    class Meta:
        model = Brief
        interfaces = (graphene.relay.Node, )

class Query(graphene.ObjectType):
    node = graphene.relay.Node.Field()
    all_briefs = MongoengineConnectionField(BriefNode)

schema = graphene.Schema(query=Query, types=[BriefNode])
query = '''
    query getBrief {
        allBriefs {
            edges {
                node {
                    topic
                }
            }
        }
    }
'''
result = schema.execute(query)
```

**Comment by sjakati98** [comment]
@abawchen I got my issue to work after "registering" my embedded documents within my schema.
