### ISSUE TITLE
What does "default_query" in flask_mongoengine example do?

### ISSUE THREAD

**Issue by riverfr0zen** [graphql-python/graphene-mongo#59]
In the [flask mongoengine example](https://github.com/graphql-python/graphene-mongo/blob/master/examples/flask_mongoengine/app.py), in app.py, a 'default_query' is declared. 

I had assumed that there was some magic in the background that would cause this default query to be populated by default when the graphiql view is requested from the browser.

However, this doesn't happen in my implementation attempt -- the query pane is just empty. The rest of the graphiql interface works just fine. Searching code in both graphene-mongo and flask-graphql doesn't seem to turn up any references to 'default_query'.

1) Is my expectation above correct, i.e. is this a way to populate the graphiql interface with a default query?

2) If the expectation is correct, then maybe it's not working for me because I'm declaring default_query within a flask app factory method? How would I set the default query in this case?

**Comment by abawchen** [comment]
@riverfr0zen : No, there is no any magic about `default_query` -- it just for convenience to copy-paste. :stuck_out_tongue_winking_eye:
