### ISSUE TITLE
Support for MultipolygonField

### ISSUE THREAD

**Issue by heron182** [graphql-python/graphene-mongo#62]
Hey guys, just came accross the need for a PolygonField representation.

I tried hacking my way into it by looking at #58 and it seemed very straightforward.

Could give it a shot and send PR if that's OK

**Comment by abawchen** [comment]
@heron182 

Thanks for the feedback! 👍 

I just refactored the way to resolve `PointField` into `type` and `coordinates` automatically, that we don't have to call `json.load` to parse `PointField`.

You can refer #64 for the detail -- it would be more complex than converting it into json string, but I think it would be more friendly for the usage.

**Comment by heron182** [comment]
Great @abawchen , I'll send a PR as soon as I can :)
