### ISSUE TITLE
InputObjectType fields from models

### ISSUE THREAD

**Issue by nephew92** [graphql-python/graphene-mongo#65]
I've used a `MongoengineObjectType` class to define the schema from model.
There's a way to use a reference model to define a `InputObjectType` or `AbstractType` class? Something like that:
```
class UserFields(graphene.AbstractType):
	class Meta:
		model = model.User

class User(graphene.ObjectType, UserFields):
	pass

class UserInput(graphene.InputObjectType, UserFields):
	pass


```

**Comment by abawchen** [comment]
@nephew92 : do you find a way to do it? if not, I will start to work on it recently.

**Comment by nephew92** [comment]
> @nephew92 : do you find a way to do it? if not, I will start to work on it recently.

hello @abawchen, I couldn't find a way to do this with graphene. I had to assign the fields from the model to InputObjectType manually, but I made my own function (and not beautiful) for this.

**Comment by abawchen** [comment]
@nephew92 : could you share your implementation? I can learn from it and try if I can hook (and refactor) it into graphene-mongo, thanks.

**Comment by nephew92** [comment]
> @nephew92 : could you share your implementation? I can learn from it and try if I can hook (and refactor) it into graphene-mongo, thanks.

I can't help with this, sorry. I'd implemented that for a company that I don't have collaboration anymore, also I don't have repo backups neither I remember the code details to how I resolved this problem.

**Comment by BenoitToulet** [comment]
Hello, I just published on a fork, a simple implementation allowing interface and input graphene objects creation based on graphene_mongo....
https://github.com/BenoitToulet/graphene-mongo/tree/feat-support-inputs-and-interfaces

**Comment by abawchen** [comment]
close due to stale, feel free to re-open it.
