### ISSUE TITLE
Allow subclassing MongoengineObjectType

### ISSUE THREAD

**Issue by tambeta** [graphql-python/graphene-mongo#68]
Right now, extending `MongoengineObjectType` by subclassing is not possible in any useful way as `__init_subclass_with_meta__` is immediately called on encountering a descendant class definition. This makes several assumptions, e.g. `Meta.model` being defined on the subclass. Extension classes might want to deduce the model via _their_ subclasses and generally wouldn't know about it at the point of class body execution.

The proposed solution is some mechanism to defer initialization until manually requested, if some flag (e.g. `manual_init`) is passed in `Meta`.

My current workaround is using multiple inheritance which allows customization. A superficial example - let's say we wish to use `quux` instead of `model` for the `Meta` key defining the model:

```python
class Enhancer:
    @classmethod
    def __init_subclass_with_meta__(cls, quux, **kwargs):
        kwargs["model"] = quux
        super().__init_subclass_with_meta__(**kwargs)        

class AssetSchema(Enhancer, MongoengineObjectType):
    class Meta:
        interfaces = (relay.Node,)
        quux = Asset
```

**Comment by zrlay** [comment]
Would following the MongoEngine API of `abstract` and `allow_inheritance` satisfy this?

**Comment by tambeta** [comment]
If you mean declaring abstract classes (meaning classes that are supposed to be subclassed - as this term isn't well defined in Python AFAIK) as

```python
class AbstractType(MongoengineObjectType):
    class Meta:
        abstract = True
```

then yes, this would be a suitable API, especially since [Graphene](https://github.com/graphql-python/graphene/) also supports it.

**Comment by tambeta** [comment]
OK, I was clearly confused earlier. For reference to others stumbling on this issue, `MongoengineObjectType` makes use of [`SubclassWithMeta`](https://github.com/graphql-python/graphene/blob/142f4a58d82635b03aec560322cc3d5f395e9910/graphene/utils/subclass_with_meta.py#L21) as it subclasses `ObjectType`, hence supports passing `abstract = True` in `Meta`. This prohibits the subclass hook from running and thus takes care of inheritance issues. Closing.

My only remaining gripe is that this should be clearly documented somewhere.
