### ISSUE TITLE
Problems When Using EmbeddedDocumentListField

### ISSUE THREAD

**Issue by sjakati98** [graphql-python/graphene-mongo#73]
Python Version: `Python 3.7`

Error: `TypeError: '<' not supported between instances of 'ID' and 'ConfigurationSpec'`

Essentially, I have an embedded document modeled as such:

```python
class ConfigurationSpec(EmeddedDocument):
     first_field = StringField(db_field="First Field")
     second_field = StringField(db_field="Second Field")
     ...
```
And then, I pull in the embedded document into a larger model. This larger model is built of embedded documents. The standalone embedded documents seem to work fine. When I use the field embedded document list field it gives me a couple of problems.

The larger document is modeled as:

```python
class LargeSpecModel(Document):
     meta = {'collection': 'specifications'}
     list_of_configs = EmbeddedDocumentListField(ConfigurationSpec)
```

This breaks 😟.

**Comment by sjakati98** [comment]
@abawchen Do you have any suggestions?

**Comment by abawchen** [comment]
@sjakati98 : Currently we only support `python 3.6`, since there are some major dependencies -- such as `mongoengin`, `graphene` -- do not support `3.7` either.

**Comment by sjakati98** [comment]
Makes sense. Thanks for the quick response.

**Comment by david2003542** [comment]
Hi @abawchen I saw the comments above. Currently, I am using python3.6 but I always got following error in graphql server
`Cannot query field \"funds\" on type \"ClientFundsType\"."`
