### ISSUE TITLE
Cannot connect to Mongo: Error: You have not defined a default connection

### ISSUE THREAD

**Issue by enzolutions** [graphql-python/graphene-mongo#75]
Hello Folks.

I tried graphene with SQLite and works like a charm, but now I am trying to use mongo DB using this project `graphql-python/graphene-mongo`.

What I did was install the following packages

```
pip install "graphene-django>=2.0"
pip install graphene-mongo
pip install djongo
```

And include the following configuration in my settings.py

```
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
        'NAME': 'mymongodb',
        'HOST': 'localhost',
        'PORT': 3501,
    }
}
```

Django connects perfectly because I can run migration and new collection was created in my new Mongo (empty) database using the following command.

```
python manage.py migrate
```

In addition, I could create a super user, with the instruction.

```
python manage.py createsuperuser
```

The admin user works like a charm.

I copy the model and schema from the example `https://github.com/graphql-python/graphene-mongo/tree/master/examples/flask_mongoengine` and is accesible via documenation in Graphiql.

But when I tried to run the following query.

```
{
  allEmployees {
    edges {
      node {
        id,
        name,
        department {
          id,
          name
        },
        roles {
          edges {
            node {
              id,
              name
            }
          }
        },
        leader {
          id,
          name
        }
        tasks {
          edges {
            node {
              name,
              deadline
            }
          }
        }
      }
    }
  }
}
```

I got the error 

```
{
  "errors": [
    {
      "message": "You have not defined a default connection",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allEmployees"
      ]
    }
  ],
  "data": {
    "allEmployees": null
  }
}
```

**Comment by enzolutions** [comment]
I figure out the connection for Django Database is different than the connection for Graphene Database for`mongoengine`.

I added this to my settings.py and my queries start to work as expected, I how this helps someone else in the future.

```
from mongoengine import connect
connect(MONGO_DATABASE_NAME, host=MONGO_HOST, port=MONGO_PORT)
```

**Comment by abawchen** [comment]
@enzolutions 

Thanks for input, and I am using the same stack (django, djongo, mongo) in my another project -- that I can integration with `graphene-mongo` now 😄
