### ISSUE TITLE
Bug in version 0.2.0 all_posts = MongoengineConnectionField(Posts)

### ISSUE THREAD

**Issue by anilwarbhe** [graphql-python/graphene-mongo#76]
After updating graphene-mongo from 0.18 to 0.2.0, I could not get "ListField(StringField())" types in query parameter. So I revert back to 0.18.
For example:

query{
  allPosts(here I can have all fields of posts collection except 'selectedtags' and 'postpics')
}

in post_model.py I have following
`class Posts(Document):
    meta = {'collection': 'posts'}
    categoryid = ReferenceField(Categories)  
    cityid = ReferenceField(City)
    pdate = DateTimeField()
    content = DictField(required = True)
    selectedtags = ListField(StringField())
    postpics = ListField(StringField())
    featured = BooleanField()`

**Comment by abawchen** [comment]
@anilwarbhe : Thanks for the feedback :)

May I know your expectation about the query?
https://docs.mongodb.com/manual/tutorial/query-arrays/#match-an-array
There a 3 cases in the document:

A. The following example queries for all documents where the field tags value is an array with exactly two elements, "red" and "blank", in the specified order:
```javascript
db.inventory.find( { tags: ["red", "blank"] } )
```

B. If, instead, you wish to find an array that contains both the elements "red" and "blank", without regard to order or other elements in the array, use the $all operator:
```javascript
db.inventory.find( { tags: { $all: ["red", "blank"] } } )
```

C. The following example queries for all documents where tags is an array that contains the string "red" as one of its elements:
```javascript
db.inventory.find( { tags: "red" } )
```

C is the easiest one to implement, and I can try A as well.
But regarding B, I have not come up with an elegant way to do it.

**Comment by abawchen** [comment]
@anilwarbhe : I enable `contains` search in `0.2.2`, if you have any question or request, feel free to reopen it or create a new one.

**Comment by anilwarbhe** [comment]
What I mean is in version 0.1.18 the following Query Works:
query{allPosts(cityid:"Q2l0eTo1YzU2Yjc5MTVkZmY5NjEzZDE2ZWQ3ZWQ=", selectedtags:"Women-Garment", first:300){edges{node{id, content, postpics, userid{id}, featured}} pageInfo { startCursor endCursor}}}

But When I update it to 0.2, Query throws an error. _**selectedtags:"Women-Garment"**_ is not allowed in the query.
query{allPosts(cityid:"Q2l0eTo1YzU2Yjc5MTVkZmY5NjEzZDE2ZWQ3ZWQ=", **_selectedtags:"Women-Garment"_**, first:300){edges{node{id, content, postpics, userid{id}, featured}} pageInfo { startCursor endCursor}}}

**Comment by abawchen** [comment]
@anilwarbhe 👍 
I think `0.2.2` can solve this issue, please give it a try.

**Comment by anilwarbhe** [comment]
pip install --upgrade graphene-mongo==0.2.2 throws error

**Comment by anilwarbhe** [comment]
Yes! Thanks a lot! Updated manually to the latest. Working now.
