### ISSUE TITLE
Filter like mongodb find

### ISSUE THREAD

**Issue by rhnux** [graphql-python/graphene-mongo#81]
Dear,

Is it possible to move the following find to a GraphQL query?

Example Mongodb: (Specifically **{ date_ar: { $regex: /23:55$/ }** )

´´´
> db.collection.find( { date_ar: { $regex: /23:55$/ }  } ).limit(30).sort( { $natural: -1 } ).pretty()
{
        "_id" : ObjectId("5cb9388e87200745fba9d727"),
        "dm3rf" : "4240.02",
        "dm3pr" : "4945.75",
        "rdm3p" : "40.67",
        "unit" : "m3",
        "dm3" : "3813.85",
        "truckm" : "477",
        "date_ar" : "2019-04-18 23:55",
        "rdm3" : "1993.03",
        "dm3rf_p" : "86.53",
        "dm3_p" : "77.83",
        "date_utc" : "2019-04-19 02:55:10.030226"
}
{
        "_id" : ObjectId("5cb7e7118720071491f42149"),
        "dm3pr" : "5623.5",
        "date_ar" : "2019-04-17 23:55",
        "dm3" : "4265.61",
        "dm3_p" : "87.05",
        "rdm3" : "3986.05",
        "date_utc" : "2019-04-18 02:55:13.017360",
        "truckm" : "533",
        "dm3rf" : "4353.11",
        "dm3rf_p" : "88.84",
        "unit" : "m3",
        "rdm3p" : "81.35"
}
´´´

Example GraphQL - (I can only select a specific day and time)

´´´
  allDaym3(dateAr: "2019-04-16 23:55") {
    edges {
      node {
        dm3
        dm3rf
        rdm3
        dm3pr
        dateAr
      }
    }
  }
´´´
´´´
{
  "data": {
    "allDaym3": {
      "edges": [
        {
          "node": {
            "dm3": "4196.06",
            "dm3rf": "4192.95",
            "rdm3": "3986.05",
            "dm3pr": "5695.5",
            "dateAr": "2019-04-16 23:55"
          }
        }
      ]
    },
´´´

**Comment by abawchen** [comment]
@rhnux : It's similar with #82, and @riverfr0zen provides https://github.com/riverfr0zen/graphene-mongo-extras to try to solve it.

**Comment by rhnux** [comment]
@abawchen @riverfr0zen 
thank you!

**Comment by riverfr0zen** [comment]
Yeah, it doesn't have a regex operator per se, since that isn't a Mongoengine query operator (although it's a good idea for a future custom operator), but for your example above you should be able to use `contains` or `icontains`.

**Comment by abawchen** [comment]
@riverfr0zen : Maybe I can try to create a PR in your repo :stuck_out_tongue:, I remember I used to take care regex query in pymongo.

Close this one.

**Comment by riverfr0zen** [comment]
@abawchen Sure. I haven't set up Travis and stuff yet, but feel free. I don't mind making you a contributor too, if you like.
