### ISSUE TITLE
Time Query Last Register

### ISSUE THREAD

**Issue by rhnux** [graphql-python/graphene-mongo#92]
Dear, 

I have the next question.

The following query with specific delay filter 118 **ms** 

<img width="1150" alt="Screen Shot 2019-05-20 at 16 21 45" src="https://user-images.githubusercontent.com/26807888/58048245-afcb0a80-7b20-11e9-81ed-db995e096419.png">

And  this with "last: 1"  delay filter 9,1 **s**

<img width="1162" alt="Screen Shot 2019-05-20 at 16 21 01" src="https://user-images.githubusercontent.com/26807888/58048479-354eba80-7b21-11e9-875f-08a4eadaefe9.png">

It's the same data. (same records)

The time is related to Waiting (TTFB).
Can you tell me if I'm making a mistake?

**Comment by abawchen** [comment]
@rhnux : it seems related to #125, and has been fixed on the updated master. Feel free to reopen it if any question.

**Comment by rhnux** [comment]
@abawchen  Ok. Thank you very much!
