### ISSUE TITLE
Limit number of results

### ISSUE THREAD

**Issue by RohitChattopadhyay** [graphql-python/graphene-mongo#95]
How to implement something like `cursor.limit(number)` ( ref: https://docs.mongodb.com/manual/reference/method/cursor.limit/ )

OR How can I restrict the number of results? The main purpose is to create pagination.

My collection has 5million documents, and thus I require pagination set up via graphql.

**Comment by abawchen** [comment]
@RohitChattopadhyay : You can try `first`, for example: https://github.com/graphql-python/graphene-mongo/blob/master/graphene_mongo/tests/test_relay_query.py#L285
