### ISSUE TITLE
Support for SequenceField

### ISSUE THREAD

**Issue by fabiontop** [graphql-python/graphene-mongo#97]
Hello everybody,
we are using the SequenceField to create Invoice Numbers. Sadly there is no integration. I get the following error:
```
Exception: Don't know how to convert the MongoEngine field <mongoengine.fields.SequenceField object at 0x10df7a908> (<class 'mongoengine.fields.SequenceField'>)

```

Is it possible to add the support? Thank you in advance :)

**Comment by abawchen** [comment]
@fabiontop : Support in 0.2.7 and updated master.
